global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Frontend monitoring
  - job_name: 'frontend'
    static_configs:
      - targets: ['frontend:3000']
    metrics_path: '/api/metrics'
    scrape_interval: 30s

  # Backend API monitoring
  - job_name: 'backend'
    static_configs:
      - targets: ['backend:3002']
    metrics_path: '/api/metrics'
    scrape_interval: 15s

  # MCP servers monitoring
  - job_name: 'mcp-git-analytics'
    static_configs:
      - targets: ['mcp-servers:8001']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'mcp-code-quality'
    static_configs:
      - targets: ['mcp-servers:8002']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'mcp-knowledge-graph'
    static_configs:
      - targets: ['mcp-servers:8003']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Neo4j monitoring
  - job_name: 'neo4j'
    static_configs:
      - targets: ['neo4j:7474']
    metrics_path: '/db/manage/server/jmx/domain/org.neo4j'
    scrape_interval: 60s

  # Redis monitoring
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s

  # Ollama monitoring
  - job_name: 'ollama'
    static_configs:
      - targets: ['ollama:11434']
    metrics_path: '/api/ps'
    scrape_interval: 60s

  # Nginx monitoring
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']
    metrics_path: '/nginx_status'
    scrape_interval: 30s

  # Node exporter for system metrics (if added)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Example alerting rules
rule_files:
  - "alert_rules.yml" 